# site properties and page defaults
title: NeuroUrology Labs
subtitle: Led by Drs. Jim Hokanson and Aaron Mickle
description: Our research focuses on studying bladder function, with a particular emphasis on neuronal control. Studies include fundamental mechanisms underlying bladder sensory function and dysfunction, development of new theraptics to treat bladder dysfucntion, and development of new and improved diagnostic testing approaches.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: contact@aamickle.com
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: aamickle
  twitter: aamickle
  youtube: aamickle

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff

# configure jekyll spaceship
jekyll-spaceship:
  mathjax-processor:
    src:
      - https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js
